wandb_version: 1

bs:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683456721.249679
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.15.2
      8:
      - 3
      - 5
