wandb_version: 1

bs:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683456576.902113
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      - 38
      4: 3.9.0
      5: 0.15.2
      8:
      - 3
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/mean_squared_error
      5: 1
      6:
      - 1
    - 1: epoch/mean_absolute_error
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
